services:
  postgres:
    image: 'postgres:13'
    container_name: 'a03-postgres'
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=a03
      - POSTGRES_PASSWORD=LEwjZrX56_U8qT#
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 1s
      retries: 60
  app:
    container_name: 'a03-app'
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy